#!/bin/bash
# Runs blockcoil evaluator based on FMDT coil evaluator.
#
# PYTHONPATH environment variable is used so it can be used 
# without PyHO being installed in the system or user Python path.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# For Cython/pyximport support.
LIBS_DIR="${DIR}/pyho/libs"

PYTHONPATH="${PYTHONPATH}:${DIR}:${LIBS_DIR}" exec "${DIR}/examples/fmdt/run_evaluator" $@
